### ISSUE TITLE
[bug] Update actionlint

### ISSUE THREAD

**Issue by ianlewis** [ianlewis/todo-issue-reopener#1278]
actionlint sometimes fails with the following error. It should be updated to see if the error goes away.

```
fatal error: concurrent map read and map write

goroutine 19 [running]:
github.com/rhysd/actionlint.(*ErrorFormatter).RegisterRule(0xc0000b5860, {0x6fe760, 0xc0001ea190})
	/home/runner/work/actionlint/actionlint/error.go:[32](https://github.com/ianlewis/todo-issue-reopener/actions/runs/11413662308/job/31761504233#step:3:33)1 +0x55
github.com/rhysd/actionlint.(*Linter).check(0xc0000bea00, {0x7fff6[33](https://github.com/ianlewis/todo-issue-reopener/actions/runs/11413662308/job/31761504233#step:3:34)a3bef, 0x20}, {0xc000190000, 0xb88, 0xb89}, 0xc00014b848, 0x0?, 0xc0000bce00, 0xc0000d8730)
	/home/runner/work/actionlint/actionlint/linter.go:583 +0x1775
github.com/rhysd/actionlint.(*Linter).LintFiles.func1()
	/home/runner/work/actionlint/actionlint/linter.go:352 +0x18a
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x96

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc00014b8c0?)
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0x6900a0?)
	/opt/hostedtoolcache/go/1.21.1/x64/src/sync/waitgroup.go:116 +0x48
golang.org/x/sync/errgroup.(*Group).Wait(0xc0000bcdc0)
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:53 +0x25
github.com/rhysd/actionlint.(*Linter).LintFiles(0xc0000bea00, {0xc0000be050, 0x5, 0x8bd2a0?}, 0x0)
	/home/runner/work/actionlint/actionlint/linter.go:363 +0xae6
github.com/rhysd/actionlint.(*Command).runLinter(0xc000145230, {0xc0000be050?, 0x5, 0x5}, 0xc0001540b0, 0x0)
	/home/runner/work/actionlint/actionlint/command.go:106 +0x170
github.com/rhysd/actionlint.(*Command).Main(0xc000145230, {0xc0000be000, 0xa, 0xa})
	/home/runner/work/actionlint/actionlint/command.go:180 +0x70c
main.main()
	/home/runner/work/actionlint/actionlint/cmd/actionlint/main.go:15 +0xcc

goroutine 18 [runnable]:
gopkg.in/yaml%2ev3.(*parser).parse(0xc000046c00)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:147 +0x1c5
gopkg.in/yaml%2ev3.(*parser).parseChild(...)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:197
gopkg.in/yaml%2ev3.(*parser).mapping(0xc000046c00)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:288 +0x253
gopkg.in/yaml%2ev3.(*parser).parse(0xc000046c00)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:155 +0xe9
gopkg.in/yaml%2ev3.(*parser).parseChild(...)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:197
gopkg.in/yaml%2ev3.(*parser).mapping(0xc000046c00)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:288 +0x253
gopkg.in/yaml%2ev3.(*parser).parse(0xc000046c00)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:155 +0xe9
gopkg.in/yaml%2ev3.(*parser).parseChild(...)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:197
gopkg.in/yaml%2ev3.(*parser).mapping(0xc000046c00)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:288 +0x253
gopkg.in/yaml%2ev3.(*parser).parse(0xc000046c00)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:155 +0xe9
gopkg.in/yaml%2ev3.(*parser).parseChild(...)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:197
gopkg.in/yaml%2ev3.(*parser).document(0xc000046c00)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:206 +0x79
gopkg.in/yaml%2ev3.(*parser).parse(0xc000046c00)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:159 +0xa5
gopkg.in/yaml%2ev3.unmarshal({0xc00006e000, 0x5077, 0x5078}, {0x6845a0, 0xc0000140a0}, 0x98?)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:161 +0x2e9
gopkg.in/yaml%2ev3.Unmarshal(...)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:89
github.com/rhysd/actionlint.Parse({0xc00006e000, 0x5077, 0x5078})
	/home/runner/work/actionlint/actionlint/parse.go:1411 +0x53
github.com/rhysd/actionlint.(*Linter).check(0xc0000bea00, {0x7fff633a3bc8, 0x26}, {0xc00006e000, 0x5077, 0x5078}, 0xc00014b848, 0x0?, 0xc0000bce00, 0xc0000d8730)
	/home/runner/work/actionlint/actionlint/linter.go:503 +0x245
github.com/rhysd/actionlint.(*Linter).LintFiles.func1()
	/home/runner/work/actionlint/actionlint/linter.go:352 +0x18a
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x96

goroutine 22 [runnable]:
gopkg.in/yaml%2ev3.(*parser).scalar(0xc000080800)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:238 +0x96
gopkg.in/yaml%2ev3.(*parser).parse(0xc000080800)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:151 +0xc5
gopkg.in/yaml%2ev3.(*parser).parseChild(...)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:197
gopkg.in/yaml%2ev3.(*parser).mapping(0xc000080800)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:280 +0x138
gopkg.in/yaml%2ev3.(*parser).parse(0xc000080800)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:155 +0xe9
gopkg.in/yaml%2ev3.(*parser).parseChild(...)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:197
gopkg.in/yaml%2ev3.(*parser).document(0xc000080800)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:206 +0x79
gopkg.in/yaml%2ev3.(*parser).parse(0xc000080800)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:159 +0xa5
gopkg.in/yaml%2ev3.unmarshal({0xc000162000, 0x10af, 0x10b0}, {0x6845a0, 0xc0001772c0}, 0x98?)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:161 +0x2e9
gopkg.in/yaml%2ev3.Unmarshal(...)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:89
github.com/rhysd/actionlint.Parse({0xc000162000, 0x10af, 0x10b0})
	/home/runner/work/actionlint/actionlint/parse.go:1411 +0x53
github.com/rhysd/actionlint.(*Linter).check(0xc0000bea00, {0x7fff633a3c5f, 0x1c}, {0xc000162000, 0x10af, 0x10b0}, 0xc00014b848, 0x0?, 0xc0000bce00, 0xc0000d8730)
	/home/runner/work/actionlint/actionlint/linter.go:503 +0x245
github.com/rhysd/actionlint.(*Linter).LintFiles.func1()
	/home/runner/work/actionlint/actionlint/linter.go:352 +0x18a
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x96
make: *** [Makefile:1[34](https://github.com/ianlewis/todo-issue-reopener/actions/runs/11413662308/job/31761504233#step:3:35): actionlint] Error 2
```

**Comment by ianlewis** [comment]
Fixed on 84221cfba017df7f3ed6e387284db818117977ace
